allowBuilds:
  '@swc/core': set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@nihilapp/diceroll-v3@3.0.4 || 3.0.5'
  - eslint-plugin-import-x@4.17.1
onlyBuiltDependencies:
  - '@swc/core'
  - unrs-resolver
